### PR TITLE
chore: fixing commitlint and adding detectOpenHandles

### PR DESCRIPTION
**Pull request by bovas85**

### CODE REVIEW

**Comment by manniL** [comment]
@bovas85 A small thing concerning commit lint (ref: https://github.com/marionebl/commitlint#getting-started)

As husky is used in dev, we possibly should alter the `$GIT_PARAMS` instead of deleting them. :thinking:

**Comment by bovas85** [comment]
I'll come back to this tomorrow. how is that changed?

**Comment by manniL** [comment]
@bovas85 Perfect!

**Comment by manniL** [comment]
Thank you for your contribution ☺️

**Comment by bovas85** [comment]
Thank you, great piece of library :)

**Pull request merged**
