### PR TITLE
Add Nuxt build indicator to whitelist

### PR DESCRIPTION
**Pull request by homerjam**

### CODE REVIEW

**Comment by manniL** [comment]
As purgecss should usually *not* run in dev mode, the build indicator shouldn't be part of the whitelist IMO.

**Comment by homerjam** [comment]
How about only if `isDev` is true?

**Comment by manniL** [comment]
> How about only if `isDev` is true?

**Comment by homerjam** [comment]
Do you prefer:

```js
// Line 28
    whitelist: ['body', 'html', 'nuxt-progress', 'nuxt__build_indicator', '__nuxt', '__layout']
      .filter(selector => this.options.dev || selector !== 'nuxt__build_indicator'),

```

or

```js
// Line 44
  if (this.options.dev) {
    defaults.whitelist.push('nuxt__build_indicator')
  }
```

**Comment by manniL** [comment]
> Do you prefer:
> 
> ```js
> // Line 28
>     whitelist: ['body', 'html', 'nuxt-progress', 'nuxt__build_indicator', '__nuxt', '__layout']
>       .filter(selector => this.options.dev || selector !== 'nuxt__build_indicator'),
> ```
> 
> or
> 
> ```js
> // Line 44
>   if (this.options.dev) {
>     defaults.whitelist.push('nuxt__build_indicator')
>   }
> ```

sorry for the late answer! The latter is preferred.

**Comment by manniL** [comment]
Please apply your changes to the most recent version and resolve merge conflicts ☺️

**Comment by homerjam** [comment]
I made #85 instead - seems better due to the refactor

**Pull request closed without merging**
